CREATE TABLE item (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL
);

CREATE TABLE book (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publisher VARCHAR(250) NOT NULL,
  cover_state VARCHAR(250) NOT NULL
);

CREATE TABLE label (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  color VARCHAR(150) NOT NULL
);

CREATE TABLE Author(
    id int generated always as identity,
    first_name varchar(255),
    last_name varchar(255),
    items text[]
    primary key (id)
    foreign key (item_id) references item(id)
);

CREATE TABLE Game(
    id int generated always as identity,
    multiplayer varchar(255),
    last_played_at date,
    published_date date,
    archived boolean,
    author_id int,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES author(id),
    primary key (id)
);

ALTER TABLE book ADD CONSTRAINT fk_book_item FOREIGN KEY (id) REFERENCES item(id) ON DELETE CASCADE;
ALTER TABLE label ADD CONSTRAINT fk_label_book FOREIGN KEY (id) REFERENCES book(id) ON DELETE CASCADE;
ALTER TABLE item ADD CONSTRAINT fk_item_book FOREIGN KEY (id) REFERENCES book(id) ON DELETE CASCADE;
